site_name: Depcore Docs
site_url: https://depcore-pl.github.io/docs/

theme:
  name: null
  custom_dir: 'depcore_theme'
  include_search_page: true
  locale: en

plugins:
  - search
  - multirepo:
      repos:
        - section: Backstage
          # you can define the edit uri path
          import_url: 'https://github.com/backstage/backstage?edit_uri=/blob/master/'
