name: build on push

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v3.9.1
    
    - uses: actions/setup-python@v5.6.0

    - name: Install dependencies
      run: make setup

    - name: Build
      run: make build
